### PR TITLE
Bind DS4 touch pad button

### PR DESCRIPTION
**Pull request by d3m3vilurr**
L3+R3 will press touch pad button

inspired [brook super converter green][1]

[1]: http://www.brookaccessory.com/detail/86711304/

### CODE REVIEW

**Comment by nefarius** [comment]
What? Why?

**Comment by d3m3vilurr** [comment]
I used moonlight on the VITA, and like this cases(other moonlight users) cannot use touchpad button in ps4 remote stream.

**Comment by nefarius** [comment]
I see but that's not really a reason to merge; users with this demand should code that the way they need it. This change would break existing implementations.

**Comment by d3m3vilurr** [comment]
ah, yeah... I understand. it can break feature, users can't press button L3/R3 at the same time anymore.
(so close this pr)

but someone still wants press touchpad button using their xb360 and xbone pad #67
I think, #76 will resolve the problem, but I want to that feature not the just simple remap, cuz playing game still need both PS button & touchpad button, so feature should be able to the binding combinations.

**Pull request closed without merging**
